export const initData = [
  {
    "divCd": null,
    "deptCd": null,
    "empCd": null,
    "insertId": null,
    "insertIp": null,
    "insertDt": null,
    "modifyId": null,
    "modifyIp": null,
    "modifyDt": null,
    "startRowIndex": null,
    "currentRowCount": null,
    "selectTotalCount": null,
    "totalCount": null,
    "patientCd": "1000",
    "patientNm": "김대영",
    "fileGroup": -1,
    "fileKey": null
  },
  {
    "divCd": null,
    "deptCd": null,
    "empCd": null,
    "insertId": null,
    "insertIp": null,
    "insertDt": null,
    "modifyId": null,
    "modifyIp": null,
    "modifyDt": null,
    "startRowIndex": null,
    "currentRowCount": null,
    "selectTotalCount": null,
    "totalCount": null,
    "patientCd": "2000",
    "patientNm": "김도건",
    "fileGroup": 31069,
    "fileKey": "MEDA0050_b089d36caa5b45bc9c52706b4b77e9a1"
  },
  {
    "divCd": null,
    "deptCd": null,
    "empCd": null,
    "insertId": null,
    "insertIp": null,
    "insertDt": null,
    "modifyId": null,
    "modifyIp": null,
    "modifyDt": null,
    "startRowIndex": null,
    "currentRowCount": null,
    "selectTotalCount": null,
    "totalCount": null,
    "patientCd": "3000",
    "patientNm": "김세영",
    "fileGroup": -1,
    "fileKey": null
  },
  {
    "divCd": null,
    "deptCd": null,
    "empCd": null,
    "insertId": null,
    "insertIp": null,
    "insertDt": null,
    "modifyId": null,
    "modifyIp": null,
    "modifyDt": null,
    "startRowIndex": null,
    "currentRowCount": null,
    "selectTotalCount": null,
    "totalCount": null,
    "patientCd": "4000",
    "patientNm": "유준영",
    "fileGroup": 31072,
    "fileKey": "MEDA0050_de717e9ae4be400bbbc07a5bf61ccaf1"
  },
  {
    "divCd": null,
    "deptCd": null,
    "empCd": null,
    "insertId": null,
    "insertIp": null,
    "insertDt": null,
    "modifyId": null,
    "modifyIp": null,
    "modifyDt": null,
    "startRowIndex": null,
    "currentRowCount": null,
    "selectTotalCount": null,
    "totalCount": null,
    "patientCd": "5000",
    "patientNm": "정영석",
    "fileGroup": -1,
    "fileKey": null
  },
  {
    "divCd": null,
    "deptCd": null,
    "empCd": null,
    "insertId": null,
    "insertIp": null,
    "insertDt": null,
    "modifyId": null,
    "modifyIp": null,
    "modifyDt": null,
    "startRowIndex": null,
    "currentRowCount": null,
    "selectTotalCount": null,
    "totalCount": null,
    "patientCd": "6000",
    "patientNm": "김재홍",
    "fileGroup": -1,
    "fileKey": null
  },
  {
    "divCd": null,
    "deptCd": null,
    "empCd": null,
    "insertId": null,
    "insertIp": null,
    "insertDt": null,
    "modifyId": null,
    "modifyIp": null,
    "modifyDt": null,
    "startRowIndex": null,
    "currentRowCount": null,
    "selectTotalCount": null,
    "totalCount": null,
    "patientCd": "7000",
    "patientNm": "강우성",
    "fileGroup": -1,
    "fileKey": null
  }
]